import json
import logging
from typing import List, Optional
from app.models.paper import StructuredPaperExtraction, ParagraphChunk
from app.services.llm_factory import LLMFactory

logger = logging.getLogger("ai_research_os.extractor")

EXTRACTION_SYSTEM_PROMPT = """You are an expert scientific AI research paper analyzer.
Your task is to extract structured JSON metadata from the provided research paper text.

Return ONLY a valid JSON object matching this schema:
{
  "title": "String title",
  "abstract": "Summary abstract of the paper",
  "primary_task": "Core research task (e.g. GraphRAG, Multi-Modal RAG, Code Generation)",
  "methodology_summary": "Core algorithmic or architecture methodology proposed",
  "datasets_used": ["dataset_1", "dataset_2"],
  "backbone_models": ["model_1", "model_2"],
  "benchmark_metrics": { "accuracy": "91.2%", "latency": "45ms", "dataset_name": "metric_value" },
  "limitations": ["limitation 1", "limitation 2"],
  "future_work": ["future direction 1"],
  "bibtex": "@article{...}"
}
Do not include markdown code block backticks if possible, just raw JSON.
"""

class PaperExtractor:

    @staticmethod
    async def extract_structured_data(
        title: str,
        abstract: str,
        paragraphs: List[ParagraphChunk],
        arxiv_id: Optional[str] = None
    ) -> StructuredPaperExtraction:
        """
        Extracts structured JSON metadata using LLMFactory (bulk workload default).
        Handles [TABLE] chunks (passed as markdown) and [MATH] chunks (preserved as-is).
        """
        # Separate tables, math, and regular text for better LLM context
        table_chunks = [p for p in paragraphs if p.text.startswith("[TABLE]")]
        regular_chunks = [p for p in paragraphs if not p.text.startswith("[TABLE]")]

        # Sample first 12 regular paragraphs (intro, methods, results sections)
        sample_texts = [p.text for p in regular_chunks[:12]]

        # Include up to 3 tables — these often contain the benchmark metrics we need
        table_texts = [p.text for p in table_chunks[:3]]

        combined_text = (
            f"TITLE: {title}\n"
            f"ABSTRACT: {abstract}\n\n"
            "CONTENT SAMPLE:\n" + "\n\n".join(sample_texts)
        )
        if table_texts:
            combined_text += "\n\nEXTRACTED TABLES (use for benchmark_metrics):\n" + "\n\n".join(table_texts)

        prompt = f"""Extract structured information from the following research paper text:

{combined_text[:7000]}

Provide the output strictly as a valid JSON object."""


        try:
            raw_response = await LLMFactory.invoke_llm(
                prompt=prompt,
                system_prompt=EXTRACTION_SYSTEM_PROMPT,
                workload_type="bulk", # Route to Ollama by default
                response_format="json_object",
                temperature=0.1
            )

            # Strip markdown block wrappers if present
            cleaned_json = raw_response.strip()
            if cleaned_json.startswith("```json"):
                cleaned_json = cleaned_json[7:]
            if cleaned_json.startswith("```"):
                cleaned_json = cleaned_json[3:]
            if cleaned_json.endswith("```"):
                cleaned_json = cleaned_json[:-3]
            cleaned_json = cleaned_json.strip()

            parsed = json.loads(cleaned_json)

            # Generate synthetic BibTeX if not generated by LLM
            if not parsed.get("bibtex"):
                key = arxiv_id or title.split()[0].lower() + "2026"
                parsed["bibtex"] = f"@article{{{key},\n  title={{{title}}},\n  journal={{arXiv preprint}},\n  year={{2026}}\n}}"

            return StructuredPaperExtraction(**parsed)

        except Exception as e:
            logger.error(f"Failed to extract structured JSON for '{title}': {e}")
            # Return a fallback StructuredPaperExtraction rather than crashing
            key = arxiv_id or "paper"
            return StructuredPaperExtraction(
                title=title,
                abstract=abstract or "Extraction pending or partially failed.",
                primary_task="General Research",
                methodology_summary="Unable to parse detailed methodology automatically.",
                datasets_used=[],
                backbone_models=[],
                benchmark_metrics={},
                limitations=["Automated extraction hit an parsing error."],
                future_work=[],
                bibtex=f"@article{{{key},\n  title={{{title}}},\n  year={{2026}}\n}}"
            )
