import json
import logging
from typing import List, Optional
from app.models.paper import StructuredPaperExtraction, ParagraphChunk
from app.services.llm_factory import LLMFactory

logger = logging.getLogger("ai_research_os.extractor")

EXTRACTION_SYSTEM_PROMPT = """You are an expert scientific AI research paper analyzer.
Your task is to extract structured JSON metadata and a dense research card from the provided research paper text.

Return ONLY a valid JSON object matching this schema:
{
  "title": "String title",
  "abstract": "Summary abstract of the paper",
  "primary_task": "Core research task (e.g. GraphRAG, Multi-Modal RAG, Code Generation)",
  "methodology_summary": "Core algorithmic or architecture methodology proposed (1-2 dense paragraphs)",
  "executive_summary": "Dense 150-word synthesis of problem, breakthrough, and results",
  "key_findings": ["Core empirical finding 1 with numbers", "Core empirical finding 2"],
  "datasets_used": ["dataset_1", "dataset_2"],
  "backbone_models": ["model_1", "model_2"],
  "benchmark_metrics": { "accuracy": "91.2%", "latency": "45ms", "dataset_name": "metric_value" },
  "limitations": ["limitation 1", "limitation 2"],
  "future_work": ["future direction 1"],
  "bibtex": "@article{...}"
}
Do not include markdown code block backticks if possible, just raw JSON.
"""

class PaperExtractor:

    @staticmethod
    async def extract_structured_data(
        title: str,
        abstract: str,
        paragraphs: List[ParagraphChunk],
        arxiv_id: Optional[str] = None
    ) -> StructuredPaperExtraction:
        """
        Extracts structured JSON metadata using LLMFactory (bulk workload default).
        Handles [TABLE] chunks (passed as markdown) and [MATH] chunks (preserved as-is).
        """
        # Separate tables, math, and regular text for better LLM context
        table_chunks = [p for p in paragraphs if p.text.startswith("[TABLE]")]
        regular_chunks = [p for p in paragraphs if not p.text.startswith("[TABLE]")]

        # Sample first 12 regular paragraphs (intro, methods, results sections)
        sample_texts = [p.text for p in regular_chunks[:12]]

        # Include up to 3 tables — these often contain the benchmark metrics we need
        table_texts = [p.text for p in table_chunks[:3]]

        combined_text = (
            f"TITLE: {title}\n"
            f"ABSTRACT: {abstract}\n\n"
            "CONTENT SAMPLE:\n" + "\n\n".join(sample_texts)
        )
        if table_texts:
            combined_text += "\n\nEXTRACTED TABLES (use for benchmark_metrics):\n" + "\n\n".join(table_texts)

        prompt = f"""Extract structured information from the following research paper text:

{combined_text[:7000]}

Provide the output strictly as a valid JSON object."""


        try:
            raw_response = await LLMFactory.invoke_llm(
                prompt=prompt,
                system_prompt=EXTRACTION_SYSTEM_PROMPT,
                workload_type="bulk", # Route to Ollama by default
                response_format="json_object",
                temperature=0.1
            )

            # Strip markdown block wrappers if present
            cleaned_json = raw_response.strip()
            if cleaned_json.startswith("```json"):
                cleaned_json = cleaned_json[7:]
            if cleaned_json.startswith("```"):
                cleaned_json = cleaned_json[3:]
            if cleaned_json.endswith("```"):
                cleaned_json = cleaned_json[:-3]
            cleaned_json = cleaned_json.strip()

            parsed = json.loads(cleaned_json)

            # Generate synthetic BibTeX if not generated by LLM
            if not parsed.get("bibtex"):
                key = arxiv_id or title.split()[0].lower() + "2026"
                parsed["bibtex"] = f"@article{{{key},\n  title={{{title}}},\n  journal={{arXiv preprint}},\n  year={{2026}}\n}}"

            return StructuredPaperExtraction(**parsed)

        except Exception as e:
            logger.error(f"Failed to extract structured JSON for '{title}': {e}")
            # Return a fallback StructuredPaperExtraction rather than crashing
            key = arxiv_id or "paper"
            return StructuredPaperExtraction(
                title=title,
                abstract=abstract or "Extraction pending or partially failed.",
                primary_task="General Research",
                methodology_summary="Unable to parse detailed methodology automatically.",
                datasets_used=[],
                backbone_models=[],
                benchmark_metrics={},
                limitations=["Automated extraction hit an parsing error."],
                future_work=[],
                bibtex=f"@article{{{key},\n  title={{{title}}},\n  year={{2026}}\n}}"
            )

    @staticmethod
    async def extract_custom_attribute(
        paper_id: str,
        paper_title: str,
        attribute_name: str,
        query_prompt: Optional[str] = None
    ) -> dict:
        """
        Dynamically extracts a specific custom question or attribute from paper paragraphs
        using hybrid vector retrieval and targeted LLM extraction (Elicit.org parity).
        """
        from app.services.vector_store import vector_store

        search_query = f"{attribute_name} {query_prompt or ''}".strip()
        matched_chunks = []
        try:
            matched_chunks = vector_store.search_paragraphs(
                query=search_query,
                top_k=4,
                paper_ids=[paper_id]
            )
        except Exception as e:
            logger.warning(f"Vector search failed for custom attribute on paper {paper_id}: {e}")

        excerpts = "\n\n".join(
            f"[Page {c.get('page_number', '?')}]: {c.get('text', '')}"
            for c in matched_chunks
        ) if matched_chunks else "No direct text chunks matched."

        prompt = f"""PAPER: {paper_title}
TARGET ATTRIBUTE / QUESTION: {attribute_name}
ADDITIONAL CLARIFICATION: {query_prompt or 'Extract the exact specific detail or metric requested.'}

PAPER EXCERPTS:
{excerpts[:4000]}

Extract the exact value for this attribute. Return ONLY a valid JSON object matching this schema:
{{
  "value": "Concise specific value (e.g. '8x NVIDIA A100 80GB', 'AdamW, lr=1e-4', '4096 tokens', '15,000 samples'). If not mentioned, state 'Not reported'.",
  "confidence": 0.85,
  "page_number": 4,
  "excerpt": "Verbatim short sentence or phrase from the paper where this was found."
}}"""

        try:
            raw = await LLMFactory.invoke_llm(
                prompt=prompt,
                system_prompt="You are a precise scientific data extraction assistant. Return only valid JSON.",
                workload_type="interactive",
                response_format="json_object",
                temperature=0.1
            )
            cleaned = raw.strip()
            if cleaned.startswith("```json"):
                cleaned = cleaned[7:]
            if cleaned.startswith("```"):
                cleaned = cleaned[3:]
            if cleaned.endswith("```"):
                cleaned = cleaned[:-3]
            data = json.loads(cleaned.strip())

            val = data.get("value", "Not reported")
            conf = float(data.get("confidence", 0.7))
            page = data.get("page_number") or (matched_chunks[0].get("page_number") if matched_chunks else None)
            excerpt = data.get("excerpt", "")

            return {
                "paper_id": paper_id,
                "attribute_name": attribute_name,
                "value": val,
                "confidence": round(conf, 2),
                "page_number": page,
                "excerpt": excerpt
            }
        except Exception as err:
            logger.error(f"Error extracting custom attribute '{attribute_name}' for {paper_id}: {err}")
            return {
                "paper_id": paper_id,
                "attribute_name": attribute_name,
                "value": "Extraction unavailable",
                "confidence": 0.0,
                "page_number": None,
                "excerpt": ""
            }

